#!/usr/bin/env bash
set -euo pipefail

# check to see if all dependencies are satisfied
function check_dependencies() {
    for dep in "op" "jq"; do
        if [[ ! $(command -v "$dep") ]]; then
            echo "Unable to find '$dep' command. Please make sure it is installed and part of the path variable."
            exit 1
        fi
    done
}

# print versions
function print_versions() {
    echo "easy-1password-cli 0.1"
    echo -n "1password-cli "
    op --version
    echo -n "jq "
    jq --version
}

# print help text
function print_help() {
    echo "TODO"
}

# check for 1password-cli to be set up
function check_for_op_setup() {
    if test -f ~/.op/config; then
        op_latest_signin=$(cat ~/.op/config | jq --raw-output '.latest_signin')
    else
        echo "1password-cli is not set up yet. Please run 'op signin' to set it up."
    fi
}

# sign in to 1password
function signin() {
    session_token=$(op signin $op_account --raw)
    session_start_time=$(date +%s)
}

# sign out of 1password
function signout() {
    op signout --session $session_token
    exit 0
}

# renew session if it is too old
function validate_session() {
    default_session_length=$((30))
    current_session_length=$(($(date +%s) - $session_start_time))
    if [[ $current_session_length -ge $default_session_length ]]; then
        echo "Your current session has expired. Please renew it to continue."
        signin
    fi
}

# prompt users for command inside the core lifecycle loop
function prompt_for_command() {
    read -p "> easy1p ($op_account): " command
    if [[ -z $command ]]; then
        prompt_for_command
    fi
    echo $command
}

# core lifecycle logic
function core_lifecycle() {
    check_for_op_setup
    op_account=${1:-$op_latest_signin}

    signin
    while :; do
        command=$(prompt_for_command)
        command_first_token=$(echo $command | head -n 1 | cut -d " " -f 1)
        [[ "$command_first_token" != "signout" && "$command_first_token" != "exit" ]] || break
        validate_session
    done
    signout
}

# entry point
function main() {
    check_dependencies

    if [[ $# -eq 1 ]]; then
        if [[ "$1" =~ ^(--?)([vV]([eE][rR][sS][iI][oO][nN])?)$ ]]; then
            print_versions
            exit 0
        fi

        if [[ "$1" =~ ^(--?)([hH]([eE][lL][pP])?)$ ]]; then
            print_help
            exit 0
        fi
    fi

    core_lifecycle $*
}

# start script
main $*

# TODO Ctrl+c Ctrl+z SIGINT catching and auto signout
# TODO Clipboard support / clear after time / clear on exit
# TODO installation and updates like oh-my-zsh
# TODO see if session variables can be stolen using op commands
# TODO check ps for session token
