#!/usr/bin/env bash

# print version
echo "easy-1password-cli 0.1"

# check for dependencies
# TODO

# check for 1password-cli updates
echo -n "1password-cli "
op --version
op update

# check for file permissions
# TODO

# TODO Shell script header
# TODO Auto update
# TODO Ctrl+c Ctrl+z SIGINT catching
# TODO Clean env variables
# TODO Auto signout
# TODO README
# TODO Clipboard management
# TODO Clipboard cleanup
